### ISSUE TITLE
頻繁に使うデータの更新をやりやすくしたい

### ISSUE THREAD

**Issue by bishopfunc** [iGEM-Waseda/igemwaseda_hp#28]
今後のiGEMerがより更新しやすい仕組みを作りたい

アイデア
1. 頻繁に更新が必要なデータを`hoge.config`に以下のように書く

```yaml
img: hoge.png
name: 早稲田太郎
team: wiki
order: 1
hobbies: null
innerText: null
```
orderは並べたときの順番 
幹事1 副幹事2 会計3

2. メンバーごとにファイルを作る
```
---/member
----/2023
-----/b1
------/waseda-taro
-------config.yaml
-------img.png
-----/b2
-----/2024
```
